# 여기는 포트 번호나 DB 등 기본적인 구성을 설정해주는 페이지입니다.

server:
  port: 9000  # 9000번 포트로 실행

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://umcdb.cbdhzgyxf31e.ap-northeast-2.rds.amazonaws.com/umcDB
    # url 형식은 jdbc:mysql://RDS의 EndPoint/내부 DB 스키마명 입니다.
    username: umcdb # 만약 따로 설정하지 않으셨다면 기본값은 admin 입니다
    password: umcdb123 # 비밀번호를 입력해주세요!
    driver-class-name: com.mysql.cj.jdbc.Driver
